name: CI With GitHub Action using xUnit - MiniStore Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore NuGet packages
      working-directory: ./MiniStoreWinF
      run: dotnet restore

    - name: Build
      working-directory: ./MiniStoreWinF
      run: dotnet build --configuration Release

    - name: Run xUnit tests
      working-directory: ./MiniStoreWinF/XUnitTest
      run: dotnet test --configuration Release --no-build
